server:
  port: 8888
  servlet:
    context-path: /example

spring:
  mqtt:
    url: tcp://127.0.0.1:1883
    userName: admin
    password: 123456
    inbound:
      clientId: iot-thinker-inbound
      topics: /test/123456
    outbound:
      clientId: iot-thinker-outbound
      topics: /test/123456
